repos:
  - repo: https://github.com/jsh9/cercis
    rev: 0.1.5
    hooks:
      - id: cercis
        args: [
          --function-definition-extra-indent=True,
          --single-quote=True,
        ]
  - repo: https://github.com/jsh9/cercis
    rev: 0.1.5
    hooks:
      - id: cercis-jupyter
        args: [
          --function-definition-extra-indent=True,
          --single-quote=True,
        ]
